#!/bin/bash

# if Docker Hub builds only for test, then $DOCKER_TAG is 'this'.
# the $DOCKER_TAG decides which FROM is will be used.
printf "hooks/build: DOCKER_TAG: %s\n" "$DOCKER_TAG"
printf "hooks/build: IMAGE_NAME: %s\n" "$IMAGE_NAME"
printf "hooks/build: DOCKERFILE_PATH: %s\n" "$DOCKERFILE_PATH"

DATE=$(date +%Y-%m-%d)

FROM_ARG=''
if [[ ! -z "${DOCKER_TAG}" ]] && [[ "$DOCKER_TAG" != 'this' ]]; then
  WEB_SERVER=$(echo $DOCKER_TAG | cut -f1 -d-)
  printf "hooks/build: WEB_SERVER: %s\n" "$WEB_SERVER"

  PHP_VERSION=$(echo $DOCKER_TAG | cut -f2 -d-)
  printf "hooks/build: PHP_VERSION: %s\n" "$PHP_VERSION"

  FROM_ARG="--build-arg FROM=webdevops/php-$WEB_SERVER-dev:$PHP_VERSION"
fi
printf "hooks/build: FROM_ARG: %s\n" "$FROM_ARG"

docker build --cache-from $IMAGE_NAME -f $DOCKERFILE_PATH -t $IMAGE_NAME -t $IMAGE_NAME-$DATE $FROM_ARG .
